In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
#### create an array of zeros with 2 rows and 10 columns

In [17]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
import numpy as np

In [22]:
np.random.rand(3,2)

array([[0.09436345, 0.00704711],
       [0.29794819, 0.39940715],
       [0.46748038, 0.66591737]])

In [23]:
np.random.randn(3,2)

array([[ 0.59773852,  1.16107092],
       [-0.2256041 ,  0.17755994],
       [-1.85440842, -0.04661472]])

In [26]:
np.random.randint(34,100)

68

In [27]:
np.random.randint(20,56,100)

array([38, 54, 23, 31, 21, 21, 36, 34, 53, 53, 49, 25, 39, 39, 26, 23, 50,
       48, 52, 40, 31, 55, 41, 39, 55, 30, 37, 27, 25, 20, 49, 46, 50, 35,
       42, 46, 40, 43, 26, 53, 43, 55, 32, 29, 45, 47, 53, 29, 44, 49, 21,
       33, 54, 32, 51, 30, 31, 48, 20, 29, 24, 55, 46, 49, 24, 42, 21, 52,
       48, 28, 28, 43, 45, 39, 38, 30, 36, 21, 38, 49, 49, 39, 37, 23, 36,
       54, 49, 32, 44, 55, 25, 25, 52, 49, 32, 32, 21, 54, 54, 31])

In [31]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
rand_array=np.random.randint(0,100,20)
rand_array

array([89, 95, 33,  6, 64, 12, 53, 88, 31, 48, 47, 71, 33, 59, 32, 18,  2,
       27, 16, 54])

In [33]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [36]:
rand_array.max()

95

In [35]:
rand_array.min()

2

In [37]:
rand_array.argmin()

16

In [38]:
rand_array.argmax()

1

In [39]:
sample_array.dtype

dtype('int64')

In [42]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
sample_array[3]

13

In [49]:
sample_array[3:7]

array([13, 14, 15, 16])

In [51]:
sample_array[1:4]

array([11, 12, 13])

In [52]:
sample_array[1:4]=100

In [53]:
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [54]:
sample_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [55]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([ 10, 100, 100, 100,  14,  15,  16])

In [56]:
subset_sample_array[1:4]=1001

In [57]:
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [58]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [59]:
### two dimensional array

In [60]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix


array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [61]:
sample_matrix[1][2]

21

In [62]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [63]:
sample_matrix[2]

array([56, 76, 24,  7])

In [64]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [65]:
#### selection techniques

In [66]:
sample_array+sample_array

array([2002, 2002, 2002, 2002, 2002, 2002, 2002,   34,   36,   38,   40])

In [68]:
np.exp(sample_array)

<ipython-input-68-90e8ad005dc7>:1: RuntimeWarning: overflow encountered in exp
  np.exp(sample_array)


array([           inf,            inf,            inf,            inf,
                  inf,            inf,            inf, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [69]:
np.log(sample_array)

array([6.90875478, 6.90875478, 6.90875478, 6.90875478, 6.90875478,
       6.90875478, 6.90875478, 2.83321334, 2.89037176, 2.94443898,
       2.99573227])

In [70]:
np.sqrt(sample_array)

array([31.63858404, 31.63858404, 31.63858404, 31.63858404, 31.63858404,
       31.63858404, 31.63858404,  4.12310563,  4.24264069,  4.35889894,
        4.47213595])

In [71]:
np.log(sample_array)

array([6.90875478, 6.90875478, 6.90875478, 6.90875478, 6.90875478,
       6.90875478, 6.90875478, 2.83321334, 2.89037176, 2.94443898,
       2.99573227])

In [72]:
np.max(sample_array)

1001

In [73]:
np.min(sample_array)

17

In [74]:
np.argmax(sample_array)

0

In [75]:
np.argmin(sample_array)

7

In [76]:
np.square(sample_array)

array([1002001, 1002001, 1002001, 1002001, 1002001, 1002001, 1002001,
           289,     324,     361,     400])

In [77]:
np.std(sample_array)

472.6278741653062

In [78]:
np.var(sample_array)

223377.1074380165

In [79]:
np.mean(sample_array)

643.7272727272727

In [84]:
array=np.random.randn(3,4)
array

array([[-0.53711897, -1.47597957, -1.28691909, -1.7641858 ],
       [-0.75219839, -1.03795003, -0.52314643,  1.43722928],
       [ 0.48038944,  1.00499481, -0.9494762 , -0.88229122]])

In [85]:
np.round(array,decimals=4)

array([[-0.5371, -1.476 , -1.2869, -1.7642],
       [-0.7522, -1.038 , -0.5231,  1.4372],
       [ 0.4804,  1.005 , -0.9495, -0.8823]])

In [86]:
sports=np.array(['golf','cricket','fball','cricket','fbal'])

In [87]:
np.unique(sports)

array(['cricket', 'fbal', 'fball', 'golf'], dtype='<U7')

In [88]:
array(['basketball','cricket','fball','glf'],dtype=<'U10')

SyntaxError: ignored